export default function getAllProducts() {
  return [
    {
      id: "66driving-1-118-FMEN-001",
      slug: "mexico-66driving-118-001-men",
      title: "Onitsuka Tiger",
      name: "Mexico 66 Driving",
      style: "Style #: 1183C306.001",
      color: "Color: Black/black",
      category: "Men's Shoe",
      categorySlug: "men-shoes",
      price: 4_100_000,
      stock: 100,
      imageUrl: "/assets/img/onit.5.jpg",
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/driving3.jpg",
        "/assets/img/driving1.jpg",
        "/assets/img/driving2.jpg",
      ],
      description: `A pair that combines the iconic MEXICO 66 model from Onitsuka Tiger with design inspiration from driving shoes. Featuring a silhouette that enhances the style of your feet and an elevated sole that offers smooth support, even while driving. The upper is crafted from clean, smooth leather, blending design appeal with comfort. For added sophistication, Alcantara, a synthetic leather often found in luxury car interiors, is used in the toe and heel areas. The insole, made from high-cushion materials, gently supports the feet for comfort even during extended wear. Details like the metal accents on the heel flap and embroidered Onitsuka Tiger stripes reflect meticulous attention to design details.`,
    },
    {
      id: "66paraty-1-118-FWOMEN-200",
      slug: "mexico-66paraty-118-200-women",
      title: "Onitsuka Tiger",
      name: "Mexico 66 Paraty",
      style: "Style #: 1183C309.200",
      color: "Color: Birch/Ivory",
      category: "Women's Shoe",
      categorySlug: "women-shoes",
      price: 2_400_000,
      stock: 5,
      imageUrl: `/assets/img/onit.4.jpg`,
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/paraty3.jpg",
        "/assets/img/paraty1.jpg",
        "/assets/img/paraty2.jpg",
      ],
      description: `The "MEXICO 66 PARATY" features a 2-way design that allows you to wear it with the heel pressed down, and now it's available in a new version with Italian recycled wool. This shoe blends casual and refined style, with soft, long-furred fabric and a checkered pattern that adds warmth to your look. Additionally, the cushioned insole provides exceptional comfort, even during long walks. A versatile pair that shines in both relaxed settings and stylish outfits, making it perfect for various occasions.`,
    },
    {
      id: "66SD-1-118-FUNISEX-401",
      slug: "mexico-66SD-118-401-unisex",
      title: "Onitsuka Tiger",
      name: "Mexico 66 SD",
      style: "Style-#: 1183C310.401",
      color: "Color: Peacoat/Peacoat",
      category: "Unisex's Shoe",
      categorySlug: "unisex-shoes",
      price: 3_300_000,
      stock: 50,
      imageUrl: `/assets/img/onit.3.jpg`,
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/sd3.jpg",
        "/assets/img/sd1.jpg",
        "/assets/img/sd2.jpg",
      ],
      description: `The "MEXICO 66 SD" is a shoe that seamlessly blends classic design with the latest technology.`,
    },
    {
      id: "mount-1-118-Fman-oo1",
      slug: "acromount--118-001-man",
      title: "Onitsuka Tiger",
      name: "Acromount",
      style: "Style #: 1183B257.001",
      color: "Color: Black/white",
      category: "Men's Shoe",
      categorySlug: "men-shoes",
      price: 2_700_000,
      stock: 0,
      imageUrl: `/assets/img/mountutm.jpg`,
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/mount3.jpg",
        "/assets/img/mount1.jpg",
        "/assets/img/mount2.jpg",
      ],
      description: `The "ACROMOUNT" is a vintage-inspired shoe drawing its design from 1970s track spikes. The upper combines fabric and leather in a perfect blend, recreating the thin forefoot and the voluminous midfoot characteristic of the original spikes. Meanwhile, the sole has been updated with a modern combination of lightweight sponge and rubber, providing exceptional comfort and durability. This ensures a comfortable fit even during extended use, making the shoe suitable for any daily scene. The large Onitsuka Tiger stripes on the upper serve as a striking accent, enhancing its classic appeal. Its versatile coloring makes it perfect for both casual and sporty styles. Enjoy your unique style with these shoes that blend history and modernity seamlessly.`,
    },
    {
      id: "silver66-1-118-Funisex-021",
      slug: "mexico-66-118-021-unisex",
      title: "Onitsuka Tiger",
      name: "Mexico 66",
      style: "Style #: 1183B566.021",
      color: "Color: Silver/off white",
      category: "Unisex's Shoe",
      categorySlug: "unisex-shoes",
      price: 2_200_000,
      stock: 2,
      imageUrl: "/assets/img/onit-6.jpg",
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/mex3.jpg",
        "/assets/img/mex1.jpg",
        "/assets/img/mex2.jpg",
      ],
      description: `The MEXICO 66™ shoe takes inspiration from several classic training shoes including the LIMBER™ shoe, which was one of the first shoes to boast the Onitsuka Tiger Stripes and were later delegated to the national Japanese team at the 1968 MEXICO Games. This look, taken directly from the ‘60s, but designed for the present, gives the MEXICO 66™ shoe its classic shape, slim styling and iconic design. Ideal for urban living, working and playing, it’s stitched with the legendary Onitsuka Tiger Stripes.`,
    },
    {
      id: "A55corsair-1-118-FWOMEN-300",
      slug: "tiger-A55corsair-118-300-women",
      title: "Onitsuka Tiger",
      name: "Tiger Corsair A55",
      style: "Style #: 1183C317.300",
      color: "Color: Lichen Green/cream",
      category: "Women's Shoe",
      categorySlug: "women-shoes",
      price: 3_200_000,
      stock: 100,
      imageUrl: "/assets/img/onit-8.jpg",
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/tiger3.jpg",
        "/assets/img/tiger1.jpg",
        "/assets/img/tiger2.jpg",
      ],
      description: `The training shoe that led the jogging boom of the 1970s, the "TIGER CORSAIR™" model has been reinterpreted for Onitsuka Tiger's 75th anniversary model. Featuring a simple and sophisticated design with a delicate appearance, you can find a pair suited for you from a wide range of color variations that combine fashion and comfort. Made with high-density textile and cowhide suede, the shoes offer a luxurious feel and throughout. The Onitsuka Tiger expressed with stitching and the heel flap and heel cross highlight brand's iconic design. Despite being lightweight, the shoes provide excellent comfort and fit. They incorporate an original sockliner that, while thin, offers superior cushioning, and provides comfort even during prolonged use.`,
    },
    {
      id: "66mexc-catctfull-s-1-118-Funisex-700",
      slug: "mexico66-cactfull-s-118-700-women",
      title: "Onitsuka Tiger",
      name: "Mexico 66 Cactfull-s",
      style: "Style #: 1183C347.700",
      color: "Color: Pink/pink",
      category: "Women's Shoe",
      categorySlug: "women-shoes",
      price: 3_200_000,
      stock: 10,
      imageUrl: "/assets/img/onit-9.jpg",
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/cact3.jpg",
        "/assets/img/cact1.jpg",
        "/assets/img/cact2.jpg",
      ],
      description: `The “MEXICO 66™ CACTFUL™-S” is where low-impact materials and fashion meet. This model is the second model utilizes materials derived from Mexican cacti. The cactus-derived material used for the upper provides both environmental consciousness and luxurious comfort. This lightweight, soft material reduces greenhouse gas emissions during manufacturing compared to real leather and cuts water usage by 99.7%. Despite its low-impact production process, it offers durability and a snug fit. The ""MEXICO 66™ CACTFUL™-S"" also excels in design, with a sleek and refined silhouette that enhances various look. Its streamlined appearance effortlessly blends with a variety of outfits. Available in classic white, pastel shades, and a calm beige, the rich color variations add a touch of individuality while maintaining a timeless design. Functionality is also a focus, with a cushioned heel wedge to ease burden on the feet. The rubber outsole provides slip resistance, even on wet surfaces, pursuing practicality without sacrificing style. In the detail such as sockliner and shoelaces also incorporates low-impact materials. About the Cactus-Derived Material This material is made from the prickly pear cactus developed by the Mexican company Adrian and Marte. As a bio-based material, it has garnered global attention for having a low impact on the environment as it does not use harmful chemicals such as phthalates or PVC (polyvinyl chloride), and requires minimal water consumption. It is known for its durability and supple texture. Onitsuka Tiger collaborated with the engineers of ""DESSERTO"" to improve the material's quality, successfully creating a new low-impact and durable material that meets Onitsuka Tiger's strict standards. For the "MEXICO 66™ CACTFUL™-S", Onitsuka Tiger's original color palette was adopted to highlight the soft texture unique to this material. The bold yet elegant pastel colors, difficult to achieve with real leather, accentuate the cactus material's flexibility and strength, creating a commanding presence. Additionally, the sole design was refined to maximize the lightweight quality of the material, ensuring a comfortable wearing experience.`,
    },
    {
      id: "mex-66-slipon-1-118-Fmen-750",
      slug: "mexico66-slip0n-118-750-men",
      title: "Onitsuka Tiger",
      name: "Mexico 66 Slip-On",
      style: "Style #: 1183C157.750",
      color: "Color: Golden Glow/cream",
      category: "Men's Shoe",
      categorySlug: "men-shoes",
      price: 2_000_000,
      stock: 83,
      imageUrl: "/assets/img/slipon.jpg",
      detailImages: [
        // Banyak gambar untuk bagian detail
        "/assets/img/663.jpg",
        "/assets/img/661.jpg",
        "/assets/img/662.jpg",
      ],
      description: `The classic Onitsuka Tiger slip-on model MEXICO 66™ SLIP-ON, now featuring a premium suede upper. Suede upper, Spare sockliner included, OrthoLite sockliner for superior cushioning, Made in Indonesia`,
    },
  ];
}
